# BUILT IN ERRORS
# EXCEPTION HOW TO HANDLE THEM
# RAISE YOUR OWN ERRORS 

# Logical errors
# indentation errors 
# SYNTAX ERROR 
# NAME ERROR WHEN YO CALL ANYTHING WHOS NOT DEFINE 
# TYPE ERROR  EX : PRINT(5+'DSFS')
# INDEX ERROR EX : L=[1,2,3] PRINT(L(4))
# VALUE ERROR 
# ATTRIBBIUTE ERROR
# KEY ERROR